export const data = [
    {
        name:"Ali",
        age:20,
        DOB:"25/5/2001",
        email:"abcd@gmail.com"
    },
    {
        name:"Ali",
        age:20,
        DOB:"25/5/2001",
        email:"abcd@gmail.com"
    },
    {
        name:"Ali",
        age:20,
        DOB:"25/5/2001",
        email:"abcd@gmail.com"
    },
    {
        name:"Ali",
        age:20,
        DOB:"25/5/2001",
        email:"abcd@gmail.com"
    },
    {
        name:"Ali",
        age:20,
        DOB:"25/5/2001",
        email:"abcd@gmail.com"
    },
    {
        name:"Ali",
        age:20,
        DOB:"25/5/2001",
        email:"abcd@gmail.com"
    },
    {
        name:"Ali",
        age:20,
        DOB:"25/5/2001",
        email:"abcd@gmail.com"
    },
    {
        name:"Ali",
        age:20,
        DOB:"25/5/2001",
        email:"abcd@gmail.com"
    },
    {
        name:"Ali",
        age:20,
        DOB:"25/5/2001",
        email:"abcd@gmail.com"
    },
    {
        name:"Ali",
        age:20,
        DOB:"25/5/2001",
        email:"abcd@gmail.com"
    },
]